name: Package

on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  Chromium:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Install required node packages
        run: npm ci
        
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for commits to version)
          fetch-depth: 0
      
      - name: Make package
        run: node scripts/build.js firefox nover

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: FastForward_chromium
          path: build/dist
          if-no-files-found: error

  Firefox:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Install required node packages
        run: npm ci
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Make package
        run: node scripts/build.js firefox nover

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: FastForward_firefox
          path: build/dist
          if-no-files-found: error
