name: Upload to store

on: 
  workflow_dispatch:

jobs:
  Build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Make package
        id: pack
        run: |
          bash scripts/firefox.sh nover
          echo "::set-output name=xpi_path::$(find ./build/dist -type f -name "*.xpi")"
        
      - name: Upload xpi
        uses: trmcnvn/firefox-addon@v1
        with:
          uuid: '{a9b6e295-9eef-451a-befb-696fbd8daa27}'
          xpi: ${{steps.pack.outputs.xpi_path}}
          manifest: build/FastForward.firefox/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
